irond:
  sources:
    scm: git
    uri: http://github.com/trustathsh/irond.git
  build: 
    tool: mvn
    commands:
      - mvn package

ifmapj:
  sources:
    scm: git
    uri: http://github.com/trustathsh/ifmapj.git
  build: 
    tool: mvn
    commands:
      - mvn package

ifmapj-examples:
  sources:
    scm: git
    uri: http://github.com/trustathsh/ifmapj-examples.git
  build: 
    tool: mvn
    commands:
      - mvn package

ifmapcli:
  sources:
    scm: git
    uri: http://github.com/trustathsh/ifmapcli.git
  build: 
    tool: mvn
    commands:
      - mvn package
  binaries: 
    path: ifmapcli-distribution/target

irongui:
  sources:
    scm: git
    uri: http://github.com/trustathsh/irongui.git
  build: 
    tool: mvn
    commands:
      - mvn package

irondetect:
  sources:
    scm: git
    uri: http://github.com/trustathsh/irondetect.git
  build: 
    tool: mvn
    commands:
      - mvn package

irondhcp:
  sources:
    scm: git
    uri: http://github.com/trustathsh/irondhcp.git
  build: 
    tool: mvn
    commands:
      - mvn package

ironvas:
  sources:
    scm: git
    uri: http://github.com/trustathsh/ironvas.git
  build:
    tool: mvn
    commands:
     - mvn package

visitmeta:
  sources:
    scm: git
    uri: https://github.com/trustathsh/visitmeta.git
  build:
    tool: mvn
    commands:
     - mvn package
  binaries: 
    path: visitmeta-distribution/target/

ironcontrol-for-android:
  sources:
    scm: git
    uri: https://github.com/trustathsh/ironcontrol-for-android.git
  build:
    tool: mvn
    commands:
     - mvn package
