#<id>
#  sources:
#    scm: <git>
#    uri: <uri>
#  build:
#    tool: <mvn>
#    commands:
#      - <list of commands>
#  binaries:
#    directories:
#      - directory:
#        source: 
#          path:
#          match:
#        destination:
#          path:
#          rename:
#    archives:
#      -archive:
#        source: 
#          path:
#          match:
#        destination:
#          path:
#          rename:
#    files:
#      - file
#        source: 
#          path:
#          match:
#        destination:
#          path:
#          rename:

irond:
  sources:
    scm: git
    uri: http://github.com/trustathsh/irond.git
  build: 
    tool: mvn
    commands:
      - mvn package
  binaries:
    archives:
      - archive: 
        source: 
          path: target
          match: irond-(\d+\.)?(\d+\.)?(\d+)-bundle\.zip$
        destination:
          path: /
          rename: irond

ifmapj:
  sources:
    scm: git
    uri: http://github.com/trustathsh/ifmapj.git
  build: 
    tool: mvn
    commands:
      - mvn package

ifmapj-examples:
  sources:
    scm: git
    uri: http://github.com/trustathsh/ifmapj-examples.git
  build: 
    tool: mvn
    commands:
      - mvn package

ifmapcli:
  sources:
    scm: git
    uri: http://github.com/trustathsh/ifmapcli.git
  build: 
    tool: mvn
    commands:
      - mvn package
  binaries: 
    archives:
      - archive:
        source:
          path: ifmapcli-distribution/target
          match: ifmapcli-distribution-(\d+\.)?(\d+\.)?(\d+)-bundle\.zip
        destination:
          path: /
          rename: ifmapcli

irongui:
  sources:
    scm: git
    uri: http://github.com/trustathsh/irongui.git
  build: 
    tool: mvn
    commands:
      - mvn package
  binaries: 
    archives:
      - archive:
        source:
          path: target
          match: irongui-(\d+\.)?(\d+\.)?(\d+)-bundle\.zip
        destination:
          path: /
          rename: irongui

irondetect:
  sources:
    scm: git
    uri: http://github.com/trustathsh/irondetect.git
  build: 
    tool: mvn
    commands:
      - mvn package
  binaries: 
    archives:
      - archive:
        source:
          path: target
          match: irondetect-(\d+\.)?(\d+\.)?(\d+)-bundle\.zip
        destination:
          path: /
          rename: irondetect

irondhcp:
  sources:
    scm: git
    uri: http://github.com/trustathsh/irondhcp.git
  build: 
    tool: mvn
    commands:
      - mvn package
  binaries: 
    archives:
      - archive:
        source:
          path: target
          match: irondhcp-(\d+\.)?(\d+\.)?(\d+)-bundle\.zip
        destination:
          path: /
          rename: irondhcp

ironvas:
  sources:
    scm: git
    uri: http://github.com/trustathsh/ironvas.git
  build:
    tool: mvn
    commands:
     - mvn package
  binaries: 
    archives:
      - archive:
        source:
          path: target
          match: ironvas-(\d+\.)?(\d+\.)?(\d+)-bundle\.zip
        destination:
          path: /
          rename: ironvas

visitmeta:
  sources:
    scm: git
    uri: https://github.com/trustathsh/visitmeta.git
  build:
    tool: mvn
    commands:
     - mvn package
  binaries: 
    archives:
      - archive:
        source:
          path: visitmeta-distribution/target
          match: visitmeta-distribution-(\d+\.)?(\d+\.)?(\d+)-bundle\.zip
        destination:
          path: /
          rename: visitmeta
