projects:

  - id: irond
    files:
     - source: irond/basicauthusers.properties
       destination: /

  - id: irondetect
    files:
      - source: irondetect/configuration.properties
        destination: /
      - source: irondetect/scenario1.pol
        destination: policies

  - id: irongui

#  - id: ironcontrol-for-android

#  - id: ifmapcli

  - id: visitmeta
    files:
      - source: visitmeta/config.properties
        destination: config

files:
  - source: README.md
    destination: /

directories:
  - source: scripts
    destination: /

execute: 
